export const GET_PRODUCT_BY_HOURS: string = 'GET_PRODUCT_BY_HOURS'
export const GET_PRODUCT_OUTPUT_OVERVIEW: string = 'GET_PRODUCT_OUTPUT_OVERVIEW'
export const GET_PRODUCT_OUTPUT_BY_DAYS: string = 'GET_PRODUCT_OUTPUT_BY_DAYS'
export const GET_PRODUCT_CUMMULATIVE_OUTPUT: string = 'GET_PRODUCT_CUMMULATIVE_OUTPUT'
export const GET_COMPARE_PRODUCT_OUTPUT: string = 'GET_COMPARE_PRODUCT_OUTPUT'

export const GET_PRODUCT_OUTPUT_OVERVIEW_FACT_DETAIL: string = 'GET_PRODUCT_OUTPUT_OVERVIEW_FACT_DETAIL'
export const GET_PRODUCT_BY_HOURS_FACT_DETAIL: string = 'GET_PRODUCT_BY_HOURS_FACT_DETAIL'
export const GET_PRODUCT_OUTPUT_BY_DAYS_FACT_DETAIL: string = 'GET_PRODUCT_OUTPUT_BY_DAYS_FACT_DETAIL'

export const GET_PRODUCT_OUTPUT_COMPARE_CHART: string = 'GET_PRODUCT_OUTPUT_COMPARE_CHART'
