export const GET_PRODUCT_BY_HOURS: string = 'GET_PRODUCT_BY_HOURS'
export const GET_PRODUCT_OUTPUT_OVERVIEW: string = 'GET_PRODUCT_OUTPUT_OVERVIEW'
export const GET_PRODUCT_OUTPUT_BY_DAYS: string = 'GET_PRODUCT_OUTPUT_BY_DAYS'